applications:
  ll_project:
    type: "composable:24.05"
    stack: "python"

    variables:
      runtime:
        python_version: 3.12

    relationships:
      database: "db:postgresql"

    web:
      commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
        "/static":
          root: "static"
          expires: 1h
          allow: true

    mounts:
      "logs":
        source: local
        source_path: logs

    hooks:
      build: |
        set -e
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements_remote.txt
        mkdir -p logs
        python3 manage.py collectstatic --noinput
      deploy: |
        python3 manage.py migrate

# force rebuild 10
