applications:
  ll_project:
    type: "composable:24.05"
    stack: "python"
    build:
      steps:
        - layer: python

    variables:
      runtime:
        python_version: 3.12

    relationships:
      database: "db:postgresql"

    web:
      commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
        "/static":
          root: "static"
          expires: 1h
          allow: true

    mounts:
      "logs":
        source: local
        source_path: logs

    hooks:
      build: |
        set -e
        python pip install --upgrade pip
        python pip install -r requirements.txt
        python pip install -r requirements_remote.txt
        mkdir -p logs
        python manage.py collectstatic --noinput
      deploy: |
        python manage.py migrate

# force rebuild 7
