# The configuration of the app when it's exposed to the web.
applications:
  ll_project:
    type: "python:3.12"
    build:
      flavor: none

    dependencies:
      python:
        pip: "24.0"

    relationships:
      database: "db:postgresql"

    web:
      commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
        "/static":
          root: "static"
          expires: 1h
          allow: true

    mounts:
      "logs":
        source: local
        source_path: logs

    hooks:
      build: |
        set -e
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        mkdir -p logs
        python manage.py collectstatic --noinput
      deploy: |
        python manage.py migrate

# force rebuild 5
